from . import mimsms_config
from . import sms_template
from . import sms_history
from . import account_move
from . import account_payment_register
from . import account_payment
from . import stock_picking
from . import res_partner
from . import sms_automation
from . import ir_actions
from . import sms_queue
